apiVersion: apps/v1
kind: Deployment
metadata:
  name: fue-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fue-app-deployment
  template:
    metadata:
      labels:
        app: fue-app-deployment
    spec:
      containers:
        - name: fue-app
          #          envFrom:
          #            - secretRef:
          #                name: tiar-app-prod-env
          image: registry.digitalocean.com/techarion-dev/fue-app:v1-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 400m
      imagePullSecrets:
        - name: techarion-dev
      restartPolicy: Always
