apiVersion: v1
kind: Service
metadata:
  name: fue-website-service
spec:
  # type: LoadBalancer
  ports:
    - protocol: TCP
      # name: http
      port: 80
      targetPort: 3000
  selector:
    app: fue-website-deployment
